name: library_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  file_picker: ^8.0.7
  url_launcher: ^6.2.4
  http: ^1.1.0
  iconsax: ^0.0.8
  get: ^4.6.5
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  firebase_auth: ^5.5.4
  syncfusion_flutter_pdfviewer: 29.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

#-------------Local Assets-------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/


